version: '3.8'

services:
  web:
    build: .
    container_name: connecteo_app
    command: gunicorn --bind 0.0.0.0:8000 connecteo.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgres://connecteo_user:password@db:5432/connecteo_db

  db:
    image: postgres:13
    container_name: connecteo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: connecteo_db
      POSTGRES_USER: connecteo_user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: