# Generated by Django 5.1.1 on 2024-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
