# Generated by Django 5.1.1 on 2024-10-22 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_profile_confirmation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="confirmation_code",
        ),
    ]
