# Generated by Django 5.1.1 on 2024-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_profile_confirmation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
